<?xml version="1.0" encoding="utf-8"?><Database Name="OlgasProject" Class="LinqToOlgaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=OlgasProject;Integrated Security=True" SettingsObjectName="Operator_Sign_Off_Sheet.Properties.Settings" SettingsPropertyName="OlgasProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.JobsTbl" Member="JobsTbls">
    <Type Name="JobsTbl">
      <Column Name="JobID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BatchNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JobIssue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SMIssue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasteType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PCBSide" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TypeOf1stOff" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeNotes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CCP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ERMN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[LineNo]" Member="LineNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Choices" Member="Choices">
    <Type Name="Choice">
      <Column Name="ChoiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChoiceText" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Operators" Member="Operators">
    <Type Name="Operator">
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PreFirstBoard" Member="PreFirstBoards">
    <Type Name="PreFirstBoard">
      <Column Name="PreFirstBoardID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PSPresentAndOk" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DrawingPresentAndOk" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BOMPresentAndOk" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BOMAndMachineJobPckMatch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OldProgramsAndDataCleared" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShimCheckOk" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CorrectChangeBotesChoiceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CorrectConcessionChoiceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CorrectERMNChoiceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReelCheckOk" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>